server:
  port: ${PORT:5000}
security:
  user:
    password: ${eureka.password}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  password: ${EUREKA_USER_PASSWORD:password}

---
spring:
  profiles: peer
eureka:
  instance:
    hostname: ${APP_NAME}.herokuapp.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_PEER_URL}/eureka/